Add html and css for adding footer
divyanshthinks/Portfolio-Divyansh pull request #5
Opened 2022-06-06 17:01 UTC by divyanshthinks

This pull request adds a footer section on the portfolio website. This pull request contains the HTML and CSS file for adding footer.

2022-06-06 17:19 UTC, ShoiraTa requested changes
Hi @divyanshthinks ,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

**First let me to point out:**

- Great commit history! ✔️ 
- You passed all the Linters! ✔️ 
- Professional pull request! ✔️ 
- Form is fully functional!

Keep on coding, good job so far! :clap:

There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

 ## Required Changes  :recycle: 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear by mentioning my Github username.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-06 17:19 UTC, ShoiraTa commented on index.html
>       <br>
- [ ] Kindly make sure that the button has the button interactions such as hover, active (when it's pressed), disabled and enable (default state) are styled as shown in the Figma template:
<img width="831" alt="Screenshot 2022-06-06 at 21 16 04" src="https://user-images.githubusercontent.com/77038610/172211574-18c5641a-8a6c-4a21-8c72-888fc22ae1d5.png">

- [ ] Kindly center the button as provided in Figma, please make sure that the placeholder text has the same styles as in Figma (font size, family, margins paddings):

Your design  | Figma design
------------- | -------------
<img width="392" alt="Screenshot 2022-06-06 at 21 17 36" src="https://user-images.githubusercontent.com/77038610/172211802-7d51a656-4bdb-4d3c-8ea3-420080c4a62a.png"> | <img width="493" alt="Screenshot 2022-06-06 at 21 17 15" src="https://user-images.githubusercontent.com/77038610/172211752-7b6dedc4-9109-4ed8-81ff-6270d3310ada.png">

2022-06-07 01:19 UTC, youmari requested changes
Hi @divyanshthinks , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Great title and short summary
✔️ NO linter error
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-07 01:19 UTC, youmari commented on index.html
>       </form>
- [ ] please make sure to implement the effect button on hover and on pressed same as the Figma design as the previous reviewer asked

2022-06-07 01:19 UTC, youmari commented on index.html
>       </form>
- [ ] [OPTIONAL] PLEASE try to add some padding to your inputs  in order to match the Figma design 
- yours
- ![image](https://user-images.githubusercontent.com/61790587/172275336-ff6562d6-8022-4676-9ed1-7c0af772cfc4.png)

2022-06-07 17:48 UTC, mukhammadrizooff approved these changes
Hi @divyanshthinks , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/l0MYKO0EWhuiZQ2RO/giphy.gif"/>


## Highlights
- All linters Passed ✔️ 
- Good implementation ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-07 17:48 UTC, mukhammadrizooff commented on index.html
>       </form>
- [ ] [OPTIONAL] Your button should `<button id="footer-button">Send</button> `  but your button text is not like this.
Please make changes!

2022-06-07 19:05 UTC, merged